version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
      - ./data:/app/data
    environment:
      - HUNTER_API_KEY=${HUNTER_API_KEY}
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000